- Classes/Service/Extractor/LanguageDetector.php
- Classes/Service/Extractor/MetaDataExtractor.php
- Classes/Service/Extractor/TextExtractor.php
> [BUGFIX] Fix use-statement for TikaServiceFactory

- Classes/Service/Tika/AppService.php
- Classes/Utility/ShellUtility.php
https://forge.typo3.org/issues/52197
not tested but should work. Especially, since the tests were OK :)
Though someone might want to create additional tests for UTF8filesystem
> [BUGFIX] correct handling of UTF8filesystem

- Classes/StatusCheck.php
- Tests/Unit/ProcessTest.php
- Tests/Unit/Service/Tika/AbstractServiceTest.php
- Tests/Unit/Service/Tika/ServiceFactoryTest.php
- Tests/Unit/Service/Tika/ServiceUnitTestCase.php
- Tests/Unit/StatusCheckTest.php
- Tests/Unit/UnitTestCase.php
Added the status check for the tika server mode
> [BUGFIX] Implemented status check for tika server mode. Fixes: #8

- ext_conf_template.txt
- ext_tables.php
Tika solr backend module is now configurable.
> [TASK] Make tika solr backend module configurable. Fixes: #7

- Classes/Backend/SolrModule/TikaControlPanelModuleController.php
- Classes/Service/Extractor/MetaDataExtractor.php
- Classes/StatusCheck.php
- Tests/Build/UnitTests.xml
- Tests/Unit/Backend/SolrModule/TikaControlPanelModuleControllerTest.php
- Tests/Unit/Service/Extractor/MetaDataExtractorTest.php
- Tests/Unit/StatusCheckTest.php
- Tests/Unit/UnitTestCase.php
Added additional testcase for
- Backend Module Controller
- StatusCheck
- MetaDataExtractor
> Extended the testsuite to have more components tested in the ci process.

- Resources/Private/Partials/FlashMessages.html
- Resources/Private/Templates/TikaControlPanelModule/Index.html
FlashMessages where not working in TYPO3 8 in the tika solr backend module.
Fixes: #22
> [BUGFIX] FlashMessages not working in TYPO3 8

- .travis.yml
- Classes/Service/Extractor/TextExtractor.php
- Tests/Integration/Service/Tika/ServerServiceTest.php
Allow zip files for text extraction
Fixes: #28
> [TASK] Added zip as supported file for text extraction.

- .travis.yml
- Classes/Service/Tika/SolrCellService.php
- composer.json
> [BUGFIX] only use the first 3 signs in version compare - release-2.1.x

- Classes/Backend/SolrModule/TikaControlPanelModuleController.php
- Classes/Process.php
- Classes/Report/TikaStatus.php
- Classes/Service/Extractor/AbstractExtractor.php
- Classes/Service/Extractor/LanguageDetector.php
- Classes/Service/Extractor/MetaDataExtractor.php
- Classes/Service/Tika/AbstractService.php
- Classes/Service/Tika/AppService.php
- Classes/Service/Tika/SolrCellService.php
- Tests/Integration/Service/Tika/ServerServiceTest.php
- Tests/Unit/Backend/SolrModule/TikaControlPanelModuleControllerTest.php
- Tests/Unit/ExecMockFunctions.php
- Tests/Unit/ExecRecorder.php
- Tests/Unit/Service/Tika/AbstractServiceTest.php
- Tests/Unit/Service/Tika/ServiceUnitTestCase.php
- Tests/Unit/UnitTestCase.php
- ext_emconf.php
> [TASK] Use bracket notation [] instead of array() where possible

- Classes/Backend/SolrModule/TikaControlPanelModuleController.php
- Classes/Report/TikaStatus.php
- Classes/Service/Extractor/AbstractExtractor.php
- Classes/Service/Extractor/LanguageDetector.php
- Classes/Service/Extractor/TextExtractor.php
- Classes/Service/Tika/AppService.php
- Classes/Service/Tika/ServerService.php
- Classes/Service/Tika/SolrCellService.php
- Tests/Integration/Service/Tika/ServerServiceTest.php
- Tests/Unit/Backend/SolrModule/TikaControlPanelModuleControllerTest.php
- Tests/Unit/ProcessTest.php
- Tests/Unit/Service/Extractor/MetaDataExtractorTest.php
- Tests/Unit/Service/Tika/AbstractServiceTest.php
- Tests/Unit/Service/Tika/AppServiceTest.php
- Tests/Unit/Service/Tika/ServerServiceTest.php
- Tests/Unit/Service/Tika/ServiceFactoryTest.php
- Tests/Unit/Service/Tika/ServiceUnitTestCase.php
- Tests/Unit/Service/Tika/SolrCellServiceTest.php
- Tests/Unit/UnitTestCase.php
- ext_emconf.php
- ext_tables.php
> [TASK] Convert array to bracket notation

- Classes/Report/TikaStatus.php
- Classes/Service/Tika/ServerService.php
- Classes/Service/Tika/ServiceFactory.php
- Classes/Service/Tika/SolrCellService.php
- Tests/Integration/Service/Tika/ServerServiceTest.php
- Tests/Unit/Backend/SolrModule/TikaControlPanelModuleControllerTest.php
- Tests/Unit/Service/Extractor/MetaDataExtractorTest.php
- Tests/Unit/Service/Tika/AbstractServiceTest.php
- Tests/Unit/Service/Tika/ServerServiceTest.php
- Tests/Unit/Service/Tika/ServiceFactoryTest.php
- Tests/Unit/Service/Tika/ServiceUnitTestCase.php
- Tests/Unit/Service/Tika/SolrCellServiceTest.php
- ext_localconf.php
- ext_tables.php
> [TASK] Use :class notation where possible

- .travis.yml
- Build/Test/UnitTests.xml
- Build/Test/bootstrap.sh
- Build/Test/cibuild.sh
- Tests/Integration/Service/Tika/ServerServiceTest.php
- Tests/Unit/Backend/SolrModule/TikaControlPanelModuleControllerTest.php
- Tests/Unit/Service/Extractor/MetaDataExtractorTest.php
- Tests/Unit/Service/Tika/ServiceUnitTestCase.php
- Tests/Unit/UnitTestCase.php
- composer.json
This pr:
* Run the tests against TYPO3 8.7
* Makes the tests compatible for phpunit 5.x
> [TASK] Run tests against 8.7

- .travis.yml
- Classes/Controller/Backend/SolrModule/TikaControlPanelModuleController.php
- Resources/Private/Language/locallang.xlf
- Resources/Private/Templates/Backend/SolrModule/TikaControlPanelModule/Index.html
- Tests/Unit/Backend/SolrModule/TikaControlPanelModuleControllerTest.php
- ext_tables.php
- new module is compatibly with EXT:solr >= 7.0 and TYPO3 CMS 8.7 LTS
fixes: #62
> [TASK] Adapt backend module for new EXT:solr

- Classes/Report/TikaStatus.php
As the extract handler is configured for lazy startups, it is possible that it's not loaded while testing. This commit improves the status check by performing a test extraction, instead of checking the plugin list.
Fixes: #56
> [BUGFIX] Fix Solr Cell status check

- Classes/Utility/FileUtility.php
> [TASK] fix typo in PHPDoc header

- Documentation/Index.rst
- README.md
Add information about how to configure the Tika app to the documentation.
> Documentation

- README.md
> [TASK] fix typos in README

- Classes/Service/Extractor/AbstractExtractor.php
- Classes/Service/Extractor/LanguageDetector.php
- Classes/Service/Extractor/MetaDataExtractor.php
- Classes/Service/Extractor/TextExtractor.php
- Classes/Service/File/SizeValidator.php
- ext_conf_template.txt
Add's the configuration "fileSizeLimit" with a default limit auf 500MB
Fixes: #76
> [TASK] Add size limit for extracted files

- Documentation/Releases/3_0.rst
- Documentation/Releases/Index.rst
This pr:
* Add's the release notes for EXT:tika 3.0.0
Fixes: #86
> [TASK] Add release notes for 3.0.0

- LICENSE.txt
- README.md
- composer.json
This pr:
* Updates the badges in the README.md
* Add the license and updates it in the composer.json file
> [TASK] Update license and badges

- .scrutinizer.yml
- .travis.yml
- Build/Test/bootstrap.sh
- Build/Test/publish_coverage.sh
This pr:
* Add's scrutinizer configuration
* Add's upload for code coverage data
> [TASK] Configure scrutinizer

- README.md
Add the coverage and rating badge from scrutinizer.
> [TASK] Add scrutinizer rating and coverage badge

- .travis.yml
This pr:
* Adapts the .travis.yml file to use apache tika 1.18
> [TASK] Use tika version 1.18 in tests

- ext_emconf.php
> [TASK] Allow to install with TYPO3 9.3

- Classes/ContextMenu/Preview.php
Fixes wrong condition that breaks the pagetree
Fixes: #99
> [BUGFIX] Fixed false condition for canHandle in Preview

- .travis.yml
- Classes/Service/Tika/SolrCellService.php
- Resources/Docker/Dockerfile
This pr:
* Uses the solr ConnectionManager in a way that the configured solr endpoint is used as read and write connection
Resolves: #107
> [TASK] Differ between read and write connection

- .travis.yml
- Resources/Docker/Dockerfile
This pr:
* Updates to Apache Tika 1.20
Fixes: #113
> [TASK] Install tika 1.20

- Classes/Service/Tika/AbstractService.php
- Classes/Service/Tika/ServerService.php
- Tests/Unit/Service/Tika/Fixtures/ServerServiceFixture.php
Add's more information to the log when tika fails
> [TASK] Improves the logging of failed tika calls

- Documentation/Includes.txt
- Documentation/Index.rst
> [BUGFIX]  missing lines in the documentation

- Build/Release/pre_upload_check.php
- Classes/Utility/FileUtility.php
- ext_tables.php
* removes TYPO3 < 8 conditional calls
* removes $_EXTKEY
* removes `if (TYPO3_MODE === 'BE')` in conf files
> [TASK] Make compatible with TYPO3 10.4  ::: fix deprecations

- Classes/Service/Extractor/MetaDataExtractor.php
- Tests/Unit/Service/Extractor/MetaDataExtractorTest.php
Fixes: #84
Cheryy-Picked from: #124
> [BUGFIX] wrong width and height properties taken from EXIF

- .github/FUNDING.yml
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/task.md
- .github/no-response.yml
Add github configuration files.
> [TASK] Configuration

- .editorconfig
Add configuration file for IDEs.
> [TASK] Development setup

- Build/Test/bootstrap.sh
Change download URL of Apache Tika app and server.
> [TASK] Download of Apache Tika

- .editorconfig
- Build/Test/bootstrap.sh
Backport of the editor and travis ci configuration files.
> [TASK:BP:6] Editor and Travis configuraiton

- .editorconfig
- .travis.yml
- Build/Test/bootstrap.sh
- composer.json
Backport of the editor and travis ci configuration files.
> [TASK:BP:5] Editor and Travis configuraiton

- .github/workflows/ci.yml
- Classes/Utility/ShellUtility.php
- README.md
> [BUGFIX:BP:10] Replace the deprecated TYPO3_OS constant usage with the new Environment API

- Classes/Service/Tika/AbstractService.php
- Classes/Service/Tika/AppService.php
- Classes/Service/Tika/ServerService.php
> [BUGFIX:BP:6] Handle custom java command options for server module as well

- Classes/Service/Tika/AbstractService.php
- Classes/Service/Tika/AppService.php
- Classes/Service/Tika/ServerService.php
> [BUGFIX:BP:10] Handle custom java command options for server module as well

- Classes/Process.php
- Classes/Service/Tika/AbstractService.php
- Classes/Service/Tika/AppService.php
> [BUGFIX:BP:11] Use always string instead of null in all trim() calls

- Classes/Process.php
- Classes/Service/Tika/AbstractService.php
- Classes/Service/Tika/AppService.php
> [BUGFIX] Use always string instead of null in all trim() calls

- ext_tables.php
> [BUGFIX:P:11] Fix deprecation in call to ExtensionUtility::registerModule properly

- .github/workflows/ci.yml
> [BUGFIX] Actions replace LOCAL_VOLUME_NAME with SOLR_VOLUME_NAME

- .gitattributes
- .gitignore
- Classes/Lowlevel/EventListener/BlindedSecrets.php
- Classes/Report/TikaStatus.php
- Classes/Service/Tika/SolrCellService.php
- Classes/Util.php
- Configuration/Services.yaml
- Tests/Integration/Service/Tika/ServiceIntegrationTestCase.php
- composer.json
- ext_conf_template.txt
This pull-request contains
* [!!![BUGFIX] SolrCell broken due of EXT:solr BC change on connection conf](https://github.com/TYPO3-Solr/ext-tika/commit/82a58f2ee48d4704a6d4f69df2e17bf3cd6c9b0c)
*  [[BUGFIX] Remove debug logging from Reports and print the troubles directly](https://github.com/TYPO3-Solr/ext-tika/pull/213/commits/f792b571c1e445e0fa6559917057ca35c95b7311)
* [[FEATURE] Blind the Solr Cell crendetials in TYPO3 configuration tools](https://github.com/TYPO3-Solr/ext-tika/commit/58ed2bc421480a29f7bf0802239233e6dfe9c2ea)
---
**Do not squash on merge!**
> !!![BUGFIX] #211 #212

- .github/ISSUE_TEMPLATE/bug_report.md
- Documentation/Releases/12_0.rst
- Documentation/Settings.cfg
- ext_emconf.php
* https://github.com/TYPO3-Solr/ext-tika/releases/tag/12.0.2
* https://docs.typo3.org/p/apache-solr-for-typo3/tika/12.0/en-us/Releases/12_0.html
---
There are many ways to get involved with Apache Solr for TYPO3:
* Submit bug reports and feature requests on [GitHub](https://github.com/TYPO3-Solr/ext-solr)
* Ask or help or answer questions in our [Slack channel](https://typo3.slack.com/messages/ext-solr/)
* Provide patches through Pull Request or review and comment on existing [Pull Requests](https://github.com/TYPO3-Solr/ext-solr/pulls)
* Go to [www.typo3-solr.com](http://www.typo3-solr.com) or call [dkd](http://www.dkd.de) to sponsor the ongoing development of Apache Solr for TYPO3
Support us by becoming an EB partner:
http://www.typo3-solr.com/en/contact/
or call:
+49 (0)69 - 2475218 0
> Release 12.0.2

- Classes/Service/Tika/SolrCellService.php
* Migrate to EXT:solr dev-main 2024.10.08 state
Fixes: #234
Depends on: [EXT:solr #4218](https://github.com/TYPO3-Solr/ext-solr/pull/4218)
> [TASK] Sync with EXT:solr dev-main

- .github/workflows/ci.yml
- Build/Test/phpstan.neon
- Classes/Process.php
- Classes/Report/TikaStatus.php
- Classes/Service/Extractor/AbstractExtractor.php
- Classes/Service/File/SizeValidator.php
- Classes/Service/Tika/ServiceFactory.php
- Tests/Integration/Service/Tika/ServiceIntegrationTestCase.php
- Tests/Unit/ExecMockFunctions.php.Hack
- composer.json
> [TASK] Remove Implicitly nullable parameter declarations deprecated
