Classes/Backend/SolrModule/TikaControlPanelModuleController.php, Classes/Service/Tika/AbstractService.php, Classes/Service/Tika/AppService.php, Classes/Service/Tika/ServerService.php, Classes/Service/Tika/ServiceInterface.php, Classes/Service/Tika/SolrCellService.php, README.md, Resources/Private/Partials/Service/Server.html, Resources/Private/Templates/TikaControlPanelModule/Index.html, Tests/Unit/Backend/SolrModule/TikaControlPanelModuleControllerTest.php, Tests/Unit/Service/Tika/SolrCellServiceTest.php
The current state of the backend module was highly coupled to the tika server service.
I've introduced to abstract methods for services "getIsAvailable" and "getEndpointIdentifier" and changed the code to work with the AbstractService
Fixes: #5 
- Fixed broken solr backend module, when not using standalone tika server.
- Added unit test and refactored backend controller
As far as i can see the output in the backend module can be improved. By merging this pull request the backend module is useable for SolrCell and the standalone tika jar file.
=> ping function missing in SolrCellService

.travis.yml, Classes/Service/Tika/SolrCellService.php, Resources/Private/Templates/TikaControlPanelModule/Index.html, Tests/Build/bootstrap.sh, Tests/Unit/Service/Tika/SolrCellServiceTest.php, ext_tables.php
* Removed usage of Button ViewHelper and use core ViewHelpers
* Use extractByQuery instead extract method (PHP 7.0 compatibility followup)
* Raised tika version to 1.12 (1.11 is no longer available and build is failing)
=> [TASK] Check compatibility with ext solr dev master and 4.0.0

.travis.yml, Classes/Report/TikaStatus.php, Classes/Service/Tika/AppService.php, Classes/Service/Tika/ServerService.php, Classes/Utility/FileUtility.php
GeneralyUtility::getFileAbsFileName could not be used for absolute path in TYPO3 8.0
Fixes: #23
=> [BUGFIX] GeneralyUtility::getFileAbsFileName could not be used for absolute path in TYPO3 8.0

Classes/Service/Tika/SolrCellService.php
* Only use the first 3 signs in version compare
Fixes: #26
=> [BUGFIX] only use the first 3 signs in version compare

.travis.yml, Build/Test/bootstrap.sh, Classes/Service/Extractor/MetaDataExtractor.php, Classes/Service/Tika/AbstractService.php, Classes/Service/Tika/AppService.php, Classes/Service/Tika/ServerService.php, Classes/Service/Tika/ServiceInterface.php, Classes/Service/Tika/SolrCellService.php, Tests/Integration/Service/Tika/ServerServiceTest.php, Tests/Unit/Service/Extractor/MetaDataExtractorTest.php, Tests/Unit/Service/Tika/AppServiceTest.php, Tests/Unit/Service/Tika/Fixtures/mimeOut
* Get mimetypes for tika app and tika server from application and added previous mimetype to solr cell extraction for backwards compatibility.
* Added --local param to bootstrapper as in EXT:solr
Fixes: #13
=> [TASK] Get supported mimetypes from tika

ext_localconf.php
Unsupported exception in ```SolrCellService::detectLanguageFromFile```
prevents file upload to be reported successfully.
Tika language extractor is now not registered when SOLR is used as extractor.
Thus not triggerring the exception.
=> [BUG] Unsupported exception leads to error in uploads

.travis.yml, Build/Test/bootstrap.sh, Classes/Service/Tika/ServerService.php, Resources/Docker/Dockerfile, Tests/Integration/Service/Tika/ServerServiceTest.php
This pr:
* Fixes the ping patter from "This is Tika Server." to "This is Tika Server"
because the output was changed to "This is Tika Server (Apache Tika 1.14). Please PUT\n".
With this changes it's compatible to 1.13
* Adds an integration test for ping to notice changes
* Use Tika 1.14 in build and for docker container
Fixes: #43
=> [TASK] Make EXT:tika compatible to Apache Tika 1.14

Classes/Report/TikaStatus.php
Java is only required in the app mode, because in the server mode tika can run on another node.
Fixes: #72
=> [TASK] Only require java for the app mode

Classes/Service/Tika/AbstractService.php
When the tempfile was allready cleanedup it is not required to unlink it.
In this case the unlinking can be skipped.
Fixes: #78
=> [BUGFIX] Unlink tempfile only when it exists

.travis.yml, Classes/Service/Tika/ServerService.php, Classes/Service/Tika/SolrCellQuery.php
The Extracting query in the solr master branch was moved. Therefore we use the location of the new extracting query.
=> [TASK] Apply changes for query refactoring

Classes/Service/Tika/AbstractService.php, Classes/Service/Tika/AppService.php, Classes/Service/Tika/SolrCellService.php, Tests/Unit/Service/Tika/SolrCellServiceTest.php
When fetching files for local processing the FAL API defines
two ways to do so.
1. Fetch the file for modification
2. Fetch the file only for reading
In the first case the consumer of the API is responsible
for cleaning the temporary file after usage.
In the second case the driver is responsible
for cleaning up the temporary file at any point in time
when the driver considers it appropriate.
Since the tika extension always fetches the file only for reading,
and the API clearly states, that for such case NO modifications
must be done to the file (and removing it is clearly a pretty severe modification),
the local file must not be removed at all.
This is important for remote storage drivers that do some optimizations
to keep the local file cached during one request, to speed up operations …
=> [BUGFIX] Do not unlink temporary files

Classes/Service/Tika/SolrCellService.php
If the solr writer cannot extract any informations for a file (and delivers an empty array), we have to check for this, before we manage the response. The function `solrResponseToArray` can only handle an array, but not null. Therefore we need this check before.
=> prevent getting exception while metadata extract

Classes/Service/Extractor/MetaDataExtractor.php, Tests/Unit/Service/Extractor/MetaDataExtractorTest.php
Issue described here: https://github.com/TYPO3-Solr/ext-tika/issues/84
=> Tika extracts and saves wrong width/height metadata of jpegs (EXIF)

Classes/Service/Extractor/AbstractExtractor.php, ext_localconf.php
To be able to extract data for files from file storages with other drivers, a
configuration option is added to the extension.
Usage:
```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['tika']['extractor']['driverRestrictions'][] = 'MaxServ.FalS3';
```
Fixes: #122, #123
=> [FEATURE] Allow driver configuration for extractor services

Classes/Service/Tika/ServerService.php, Tests/Integration/Service/Tika/Fixtures/ServerServiceFixture.php
The implementation to fetch website content based on the stream context and
method 'file_get_content()' is removed. Instead the TYPO3 build in
HTTP client is in use to access the Tika server. This client supports
PSR-18 and allows to use proxy information configured in TYPO3.
Internally the string representation replaced by the URI interface.
This allows an easier and better way to handle server URIs.
Fixes: #154
=> [TASK] Introduce TYPO3 PSR-18 client

Classes/Report/TikaStatus.php, Classes/Service/Extractor/AbstractExtractor.php, Classes/Service/Tika/AbstractService.php, Classes/Service/Tika/AppService.php, Classes/Service/Tika/ServerService.php, Tests/Integration/Service/Tika/AppServiceTest.php, Tests/Integration/Service/Tika/ServerServiceTest.php, Tests/Integration/Service/Tika/SolrCellServiceTest.php, Tests/Unit/UnitTestCase.php, composer.json
This pull request replace the use of the LogManager with the LoggerAwareInterface and LoggerAwareTrait.
This allows TYPO3 to inject the required log manager.
The use of numbers for the log severity, replaced with PSR LogLevel constants.
Overall the default log level is now DEBUG.
Additionally the integration and unit tests have been improved to run with the solr-ddev development environment.
Resolves: #137, #160
=> [TASK] Refactor logging

Classes/Utility/ShellUtility.php
Use the new Environment API to detect the OS instead of the deprecated TYPO3_OS constant
=> [BUGFIX] Replace TYPO3_OS with Environment (resolves #168)

Classes/Service/Tika/AppService.php, Tests/Integration/Service/Tika/AppServiceTest.php, Tests/Integration/Service/Tika/ServiceIntegrationTestCase.php, ext_conf_template.txt
This commit introduces the ability to provide additional command options. They are passed to the Java command when using the tika app. For safety reasons, only a small subset of command options can be configured:
* `-Dfoo=bar`
* `-Dfoo='hello world'`
* `-Dfoo="hello world"`
The command options can be configured via extension configuration `javaCommandOptions`.
=> [FEATURE] Allow definition of additional Java command options

Classes/Service/Tika/AppService.php, Tests/Integration/Service/Tika/AppServiceTest.php, Tests/Integration/Service/Tika/ServiceIntegrationTestCase.php, ext_conf_template.txt
**Backport of #172 for 10.0.x**
---
This commit introduces the ability to provide additional command options. They are passed to the Java command when using the tika app. For safety reasons, only a small subset of command options can be configured:
* `-Dfoo=bar`
* `-Dfoo='hello world'`
* `-Dfoo="hello world"`
The command options can be configured via extension configuration `javaCommandOptions`.
=> [FEATURE:BP:10] Allow definition of additional Java command options

Classes/Service/Tika/AppService.php, Tests/Integration/Service/Tika/AppServiceTest.php, Tests/Integration/Service/Tika/ServiceIntegrationTestCase.php, ext_conf_template.txt
**Backport of #172 for 6.0.x**
---
This commit introduces the ability to provide additional command options. They are passed to the Java command when using the tika app. For safety reasons, only a small subset of command options can be configured:
* `-Dfoo=bar`
* `-Dfoo='hello world'`
* `-Dfoo="hello world"`
The command options can be configured via extension configuration `javaCommandOptions`.
=> [FEATURE:BP:6] Allow definition of additional Java command options

Classes/Service/Tika/AbstractService.php, Classes/Service/Tika/AppService.php, Classes/Service/Tika/ServerService.php
This PR is a follow-up to #172.
---
In #172, the possibility to define custom java command options has been added. However, this was only provided for the Tika app. When using a Tika server module, direct calls to the `java` executable are triggered as well, therefore the custom command options are now applied there as well.
=> [BUGFIX] Handle custom java command options for server module as well

.php-cs-fixer.php, Classes/Service/Tika/ServerService.php, Tests/Integration/Service/Tika/ServiceIntegrationTestCase.php, composer.json
This change contains: 
* The PSR12 rule for import type blocks for PhpcsFixer  The ordered_imports.imports_order is now  class, function, const
* the coding standards fixes for TYPO3 12+ as well.
=> [TASK] Fix TYPO3 coding standards differences between PHP versions

ext_tables.php
Fix deprecation in call to ExtensionUtility::registerModule with argument $extensionName
=> [TASK] Fix deprecation in call to ExtensionUtility::registerModule 

.github/ISSUE_TEMPLATE/bug_report.md, Documentation/Releases/12_0.rst, Documentation/Settings.cfg, ext_emconf.php
**Note:** 
This release is especially relevant for Apache Solr Cell/server users. To be able to use Apache Solr server as extractor, the Solr "path", "port", and if used the "username" and "passord" must be adjusted.
* https://github.com/TYPO3-Solr/ext-tika/releases/tag/12.0.1
* https://docs.typo3.org/p/apache-solr-for-typo3/tika/12.0/en-us/Releases/12_0.html
---
There are many ways to get involved with Apache Solr for TYPO3:
* Submit bug reports and feature requests on [GitHub](https://github.com/TYPO3-Solr/ext-solr)
* Ask or help or answer questions in our [Slack channel](https://typo3.slack.com/messages/ext-solr/)
* Provide patches through Pull Request or review and comment on existing [Pull Requests](https://github.com/TYPO3-Solr/ext-solr/pulls)
* Go to …
=> Release 12.0.1

Documentation/Settings.cfg
This PR fixes the repository URL in the documentation as it was set to https://github.com/TYPO3-Solr/ext-solr instead of https://github.com/TYPO3-Solr/ext-tika.
=> [DOCS] Fix repository URL in documentation

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/ci.yml, Build/Test/IntegrationTests.xml, Build/Test/UnitTests.xml, Classes/Process.php, Documentation/Releases/12_0.rst, Documentation/Releases/13_0.rst, Documentation/Settings.cfg, Tests/Integration/Service/Tika/ServerServiceTest.php, Tests/Unit/Service/Tika/AbstractServiceTestBase.php, Tests/Unit/Service/Tika/AppServiceTest.php, Tests/Unit/Service/Tika/ServerServiceTest.php, Tests/Unit/Service/Tika/SolrCellServiceTest.php, composer.json, ext_emconf.php
This is a first alpha release for upcoming TYPO3 13 LTS
*   [TASK] Prepare main branch for TYPO3 13 by @dkd-kaehm
*   [TASK] Update to typo3/coding-standards v0.8.0 by @dkd-friedrich
*   [TASK] Update PHPUnit and testing framework by @dkd-friedrich
*   [TASK] Update dependencies for TYPO3 13.0.x by @dkd-friedrich
*   [TASK] Replace cibuild.sh by @dkd-friedrich
Please read the release notes:
https://github.com/TYPO3-Solr/ext-tika/releases/tag/13.0.0-alpha-1
---
How to Get Involved
There are many ways to get involved with Apache Solr for TYPO3:
* Submit bug reports and feature requests on GitHub
* Ask or help or answer questions in our Slack channel
* Provide patches through pull requests or review and comment on
existing pull requests
* Go to …
=> [RELEASE] 13.0.0-alpha-1

.github/workflows/ci.yml, Classes/ViewHelpers/Backend/IsStringViewHelper.php, Resources/Public/JavaScript/ContextMenuActions.js, composer.json
* Migrate ContextMenuActions.js to non jQuery version.
* Migrate to Fluid 4+
Fixes: #234
=> [FIX] TIKA-Preview does not work on TYPO3 13.4+
